const defaultTheme = require("tailwindcss/defaultTheme");
const colors = require("tailwindcss/colors");

const additionalSpacing = {
    14: "3.5rem",
    84: "21rem",
    160: "40rem",
};

module.exports = {
    purge: [
        "./resources/**/*.blade.php",
        "./resources/**/*.html",
        "./resources/**/*.vue",
    ],
    theme: {
        fontFamily: {
            sans: ["Poppins", ...defaultTheme.fontFamily.sans],
        },
        extend: {
            width: {
                "full-16": "calc(100% + 64px)",
                "full-21": "calc(100% + 84px)",
                "full-24": "calc(100% + 96px)",
                "full-39.25": "calc(100% + 114px)",
                "full-side": "calc(100% - 256px)",
                12.5: "50px",
                18.5: "74px",
                25: "100px",
                33: "132px",
                35: "140px",
                42.5: "170px",
                47.5: "190px",
                51: "204px",
                65.5: "262px",
                68.5: "274px",
                70: "280px",
                73: "292px",
                75: "300px",
                79: "316px",
                84: "336px",
                85.75: "343px",
                90: "360px",
                97.5: "390px",
                99: "396px",
                105: "420px",
                108: "432px",
                113: "452px",
                115: "460px",
                125: "500px",
                131: "524px",
                137.5: "550px",
                145: "580px",
                152.5: "610px",
                157.25: "629px",
                170.5: "682px",
                177.25: "709px",
                184: "736px",
                244: "976px",
                278.25: "1113px",
                335: "1340px",
            },
            backgroundColor: {
                graydi: "#EEF0F6",
                bluedy: "#D7E1FC",
            },
            gap: {
                18: "72px",
                22.25: "89px",
            },
            padding: {
                4.5: "18px",
                7.5: "30px",
                8.5: "34px",
                18: "72px",
                19.5: "78px",
                22: "88px",
                22.5: "90px",
                23: "92px",
                26.75: "107px",
                43.5: "174px",
                64.5: "258px",
                91.25: "365px",
            },
            minHeight: {
                100: "400px",
                125: "500px",
                screenCustom: "calc(100vh - 560px)",
            },
            maxWidth: {
                29: "84px",
                47.5: "200px",
                66.5: "266px",
                70: "280px",
                75: "300px",
                81.75: "327px",
                87.75: "351px",
                89.71: "359px",
                93.25: "373px",
                98.25: "393px",
                100: "400px",
                107.5: "430px",
                107.75: "431px",
                113: "452px",
                118.75: "475px",
                119: "476px",
                124: "496px",
                131: "524px",
                136.25: "545px",
                140.5: "562px",
                152.25: "609px",
                164.25: "627px",
                164.5: "658px",
                184.75: "739px",
                211.1: "958px",
                360: "1440px",
            },
            height: {
                87.5: "350px",
                75: "300px",
                12.5: "50px",
                18: "72px",
                22: "88px",
                65.5: "262px",
                "full--19.5": "calc(100% - 78px)",
                "full--50": "calc(100% - 200px)",
            },
            spacing: {
                4.25: "17px",
                15.25: "61px",
                18: "72px",
                21.5: "86px",
                22: "88px",
                23: "92px",
                26: "104px",
            },
            fontSize: {
                7: "28px",
                9: "32px",
                5: "40px",
                13.5: "56px",
            },
            lineHeight: {
                9.2: "36px",
                15: "60px",
                16: "64px",
                22: "44px",
            },
            animation: {
                "spin-slow": "spin 1.5s linear infinite",
            },
            boxShadow: {
                subtle: "0px 0px 32px 0px rgba(136, 152, 170, 0.15)",
                general:
                    "0px 1px 3px rgb(0 0 0 / 12%), 0 1px 2px rgb(0 0 0 / 24%);",
                input: "0px 1px 5px rgba(0, 0, 0, 0.24)",
                fb: "0px 1px 5px 0px rgba(0, 0, 0, 0.25)",
            },
            outline: {
                transparent: "0px solid transparent",
            },
            borderRadius: {
                2.5: "10px",
                5: "20px",
                16: "16px",
                8: "8px",
                xl: "1rem",
                "2xl": "2rem",
            },
            colors: {
                cyan: colors.cyan,
                darkes: "#3D465B",

                gray: {
                    ...colors.blueGray,
                    150: "#F4F7FA",
                    850: "#222938",
                    1000: "#EEF0F6",
                    1200: "#ACBADC",
                    1250: "#D7E1FC",
                    1300: "#7C8498",
                    1350: "#3D465B",
                    DAE1: "#3D465B",
                    area: "#D3D6DF",
                },

                mono: colors.gray,
                navy: {
                    100: "#E6E7EA",
                    200: "#C2C4CC",
                    300: "#999CAA",
                    400: "#707487",
                    500: "#51576E",
                    600: "#323954",
                    700: "#2D334D",
                    800: "#262C43",
                    850: "#1F243A",
                    900: "#131729",
                    1000: "#EEF0F6",
                    1350: "#3D465B",
                    2000: "#DAE1F2",
                },
                orange: colors.orange,
                theme: {
                    base: "var(--color-base)",
                    "base-contrast": "var(--color-base-contrast)",
                    "base-subtle": "var(--color-base-subtle)",
                    "base-subtle-contrast": "var(--color-base-subtle-contrast)",
                    card: "var(--color-card)",
                    "card-contrast": "var(--color-card-contrast)",
                    danger: "var(--color-danger)",
                    "danger-contrast": "var(--color-danger-contrast)",
                    "danger-hover": "var(--color-danger-hover)",
                    "danger-hover-contrast":
                        "var(--color-danger-hover-contrast)",
                    info: "var(--color-info)",
                    "info-contrast": "var(--color-info-contrast)",
                    "info-hover": "var(--color-info-hover)",
                    "info-hover-contrast": "var(--color-info-contrast-hover)",
                    primary: "var(--color-primary)",
                    "primary-contrast": "var(--color-primary-contrast)",
                    "primary-hover": "var(--color-primary-hover)",
                    "primary-hover-contrast":
                        "var(--color-primary-hover-contrast)",
                    "primary-subtle": "var(--color-primary-subtle)",
                    "primary-subtle-contrast":
                        "var(--color-primary-subtle-contrast)",
                    "primary-subtle-hover": "var(--color-primary-subtle-hover)",
                    "primary-subtle-hover-contrast":
                        "var(--color-primary-subtle-hover-contrast)",
                    success: "var(--color-success)",
                    "success-contrast": "var(--color-success-contrast)",
                    "success-hover": "var(--color-success-hover)",
                    "success-hover-contrast":
                        "var(--color-success-hover-contrast)",
                    warning: "var(--color-warning)",
                    "warning-contrast": "var(--color-warning-contrast)",
                    "warning-hover": "var(--color-warning-hover)",
                    "warning-hover-contrast":
                        "var(--color-warning-hover-contrast)",
                },
            },
            margin: {
                px: "1px",
                4.5: "18px",
                13.5: "54px",
                14.5: "58px",
                22.5: "90px",
                68.5: "274px",
                110: "110px",
            },
            minWidth: {
                ...defaultTheme.spacing,
                ...additionalSpacing,
            },
            ringColor: {
                primary: "var(--ring-color-primary)",
            },
            spacing: additionalSpacing,
            transitionProperty: {
                height: "height",
                spacing: "margin, padding",
            },
        },
    },
    variants: {
        accessibility: ["responsive", "focus-within", "focus"],
        alignContent: ["responsive"],
        alignItems: ["responsive"],
        alignSelf: ["responsive"],
        animation: ["responsive"],
        appearance: ["responsive"],
        backgroundAttachment: ["responsive"],
        backgroundClip: ["responsive"],
        backgroundColor: [
            "responsive",
            "dark",
            "group-hover",
            "focus-within",
            "hover",
            "focus",
        ],
        backgroundImage: ["responsive"],
        backgroundOpacity: [
            "responsive",
            "group-hover",
            "focus-within",
            "hover",
            "focus",
        ],
        backgroundPosition: ["responsive"],
        backgroundRepeat: ["responsive"],
        backgroundSize: ["responsive"],
        borderCollapse: ["responsive"],
        borderColor: [
            "responsive",
            "dark",
            "group-hover",
            "focus-within",
            "hover",
            "focus",
        ],
        borderOpacity: [
            "responsive",
            "group-hover",
            "focus-within",
            "hover",
            "focus",
        ],
        borderRadius: ["responsive", "hover"],
        borderStyle: ["responsive"],
        borderWidth: ["responsive", "hover"],
        boxShadow: [
            "responsive",
            "group-hover",
            "focus-within",
            "hover",
            "focus",
        ],
        boxSizing: ["responsive"],
        clear: ["responsive"],
        container: ["responsive"],
        cursor: ["responsive"],
        display: ["responsive"],
        divideColor: ["responsive", "dark"],
        divideOpacity: ["responsive"],
        divideStyle: ["responsive"],
        divideWidth: ["responsive"],
        fill: ["responsive"],
        flex: ["responsive"],
        flexDirection: ["responsive"],
        flexGrow: ["responsive"],
        flexShrink: ["responsive"],
        flexWrap: ["responsive"],
        float: ["responsive"],
        fontFamily: ["responsive"],
        fontSize: ["responsive"],
        fontSmoothing: ["responsive"],
        fontStyle: ["responsive"],
        fontVariantNumeric: ["responsive"],
        fontWeight: ["responsive", "hover", "focus"],
        gap: ["responsive"],
        gradientColorStops: ["responsive", "dark", "hover", "focus"],
        gridAutoColumns: ["responsive"],
        gridAutoFlow: ["responsive"],
        gridAutoRows: ["responsive"],
        gridColumn: ["responsive"],
        gridColumnEnd: ["responsive"],
        gridColumnStart: ["responsive"],
        gridRow: ["responsive"],
        gridRowEnd: ["responsive"],
        gridRowStart: ["responsive"],
        gridTemplateColumns: ["responsive"],
        gridTemplateRows: ["responsive"],
        height: ["responsive"],
        inset: ["responsive"],
        justifyContent: ["responsive"],
        justifyItems: ["responsive"],
        justifySelf: ["responsive"],
        letterSpacing: ["responsive"],
        lineHeight: ["responsive"],
        listStylePosition: ["responsive"],
        listStyleType: ["responsive"],
        margin: ["responsive", "hover"],
        maxHeight: ["responsive"],
        maxWidth: ["responsive"],
        minHeight: ["responsive"],
        minWidth: ["responsive"],
        objectFit: ["responsive"],
        objectPosition: ["responsive"],
        opacity: [
            "responsive",
            "group-hover",
            "focus-within",
            "hover",
            "focus",
        ],
        order: ["responsive"],
        outline: ["responsive", "focus-within", "focus"],
        overflow: ["responsive"],
        overscrollBehavior: ["responsive"],
        padding: ["responsive", "hover"],
        placeContent: ["responsive"],
        placeItems: ["responsive"],
        placeSelf: ["responsive"],
        placeholderColor: ["responsive", "dark", "focus"],
        placeholderOpacity: ["responsive", "focus"],
        pointerEvents: ["responsive"],
        position: ["responsive"],
        resize: ["responsive"],
        ringColor: ["responsive", "dark", "focus-within", "focus"],
        ringOffsetColor: ["responsive", "dark", "focus-within", "focus"],
        ringOffsetWidth: ["responsive", "focus-within", "focus"],
        ringOpacity: ["responsive", "focus-within", "focus"],
        ringWidth: ["responsive", "focus-within", "focus"],
        rotate: ["responsive", "hover", "focus"],
        scale: ["responsive", "hover", "focus"],
        skew: ["responsive", "hover", "focus"],
        space: ["responsive"],
        stroke: ["responsive"],
        strokeWidth: ["responsive"],
        tableLayout: ["responsive"],
        textAlign: ["responsive"],
        textColor: [
            "responsive",
            "dark",
            "group-hover",
            "focus-within",
            "hover",
            "focus",
        ],
        textDecoration: [
            "responsive",
            "group-hover",
            "focus-within",
            "hover",
            "focus",
        ],
        textOpacity: [
            "responsive",
            "group-hover",
            "focus-within",
            "hover",
            "focus",
        ],
        textOverflow: ["responsive"],
        textTransform: ["responsive"],
        transform: ["responsive"],
        transformOrigin: ["responsive"],
        transitionDelay: ["responsive"],
        transitionDuration: ["responsive"],
        transitionProperty: ["responsive"],
        transitionTimingFunction: ["responsive"],
        translate: ["responsive", "hover", "focus"],
        userSelect: ["responsive"],
        verticalAlign: ["responsive"],
        visibility: ["responsive"],
        whitespace: ["responsive"],
        width: ["responsive"],
        wordBreak: ["responsive"],
        zIndex: ["responsive", "focus-within", "focus"],
    },
    plugins: [
        require("@tailwindcss/typography"),
        require("@tailwindcss/forms"),
    ],
};
