export default {
    showMenu: false,
    menu: {
      main: {
        children: {
          dashboard: {
            children: false,
            icon: "icon-home",
            label: "Dashboard",
            requiresAllPermissions: [],
            requiresAnyPermissions: [],
            route: "admin.index",
          },
        },
        label: "Main",
        requiresAllPermissions: [],
        requiresAnyPermissions: [],
        showLabel: false,
      },
      cms: {
        children: {
          pages: {
            activeRoutes: [
              "admin.cms.pages.index",
              "admin.cms.pages.create",
              "admin.cms.pages.edit",
            ],
            children: {
              index: {
                icon: false,
                label: "View Pages",
                requiresAllPermissions: ["cms_page.view"],
                requiresAnyPermissions: [],
                route: "admin.cms.pages.index",
              },
              create: {
                children: false,
                icon: false,
                label: "Create Page",
                requiresAllPermissions: ["cms_page.create"],
                requiresAnyPermissions: [],
                route: "admin.cms.pages.create",
              },
            },
            icon: "icon-layout-navbar",
            label: "Pages",
            requiresAllPermissions: [],
            requiresAnyPermissions: ["cms_page.create", "cms_page.view"],
          },
          layouts: {
            activeRoutes: [
              "admin.cms.layouts.index",
              "admin.cms.layouts.create",
              "admin.cms.layouts.edit",
            ],
            children: {
              index: {
                icon: false,
                label: "View Layouts",
                requiresAllPermissions: ["cms_advanced.view"],
                requiresAnyPermissions: [],
                route: "admin.cms.layouts.index",
              },
              create: {
                children: false,
                icon: false,
                label: "Create Layout",
                requiresAllPermissions: ["cms_advanced.create"],
                requiresAnyPermissions: [],
                route: "admin.cms.layouts.create",
              },
            },
            icon: "icon-layout",
            label: "Layouts",
            requiresAllPermissions: [],
            requiresAnyPermissions: [
              "cms.create",
              "cms.view",
              "cms_advanced.view",
            ],
          },
          templates: {
            activeRoutes: [
              "admin.cms.templates.index",
              "admin.cms.templates.create",
              "admin.cms.templates.edit",
            ],
            children: {
              index: {
                icon: false,
                label: "View Templates",
                requiresAllPermissions: ["cms_advanced.view"],
                requiresAnyPermissions: [],
                route: "admin.cms.templates.index",
              },
              create: {
                children: false,
                icon: false,
                label: "Create Template",
                requiresAllPermissions: ["cms_advanced.create"],
                requiresAnyPermissions: [],
                route: "admin.cms.templates.create",
              },
            },
            icon: "icon-template",
            label: "Templates",
            requiresAllPermissions: [],
            requiresAnyPermissions: ["cms_page.create"],
          },
          menus: {
            activeRoutes: [
              "admin.cms.menus.index",
              "admin.cms.menus.create",
              "admin.cms.menus.edit",
            ],
            children: {
              index: {
                icon: false,
                label: "View Menus",
                requiresAllPermissions: ["cms.view"],
                requiresAnyPermissions: [],
                route: "admin.cms.menus.index",
              },
              create: {
                children: false,
                icon: false,
                label: "Create Menu",
                requiresAllPermissions: ["cms.create"],
                requiresAnyPermissions: [],
                route: "admin.cms.menus.create",
              },
            },
            icon: "icon-columns",
            label: "Menus",
            requiresAllPermissions: [],
            requiresAnyPermissions: ["cms.create", "cms.view"],
          },
        },
        label: "CMS",
        requiresAllPermissions: [],
        requiresAnyPermissions: [
          "cms.edit",
          "cms.create",
          "cms.view",
          "cms_post.create",
          "cms_post.view",
          "cms_page.create",
          "cms_page.view",
          "cms_product.create",
          "cms_product.view",
          "cms_team.view",
        ],
        showLabel: true,
      },
      crm: {
        children: {
          forms: {
            activeRoutes: [
              "admin.crm.forms.index",
              "admin.crm.forms.create",
              "admin.crm.forms.edit",
              "admin.crm.form-submissions.index",
              "admin.crm.form-submissions.show",
            ],
            children: {
              index: {
                icon: false,
                label: "View Forms",
                requiresAllPermissions: ["crm_forms.view"],
                requiresAnyPermissions: [],
                route: "admin.crm.forms.index",
              },
              create: {
                children: false,
                icon: false,
                label: "Create Form",
                requiresAllPermissions: ["crm_forms.create"],
                requiresAnyPermissions: [],
                route: "admin.crm.forms.create",
              },
              submissions: {
                activeRoutes: [
                  "admin.crm.form-submissions.index",
                  "admin.crm.form-submissions.show",
                ],
                icon: false,
                label: "View Form Submissions",
                requiresAllPermissions: ["crm_forms.create"],
                requiresAnyPermissions: [],
                route: "admin.crm.form-submissions.index",
              },
            },
            icon: "icon-forms",
            label: "Forms",
            requiresAllPermissions: [],
            requiresAnyPermissions: [
              "crm_forms.create",
              "crm_forms.view",
              "crm_form_submissions.view",
            ],
          },
          contacts: {
            activeRoutes: [
              "admin.crm.contacts.index",
              "admin.crm.contacts.create",
              "admin.crm.contacts.edit",
            ],
            children: {
              index: {
                icon: false,
                label: "View Contacts",
                requiresAllPermissions: ["crm_contacts.create"],
                requiresAnyPermissions: [],
                route: "admin.crm.contacts.index",
              },
              create: {
                children: false,
                icon: false,
                label: "Create Contact",
                requiresAllPermissions: ["crm_contacts.create"],
                requiresAnyPermissions: [],
                route: "admin.crm.contacts.create",
              },
            },
            icon: "icon-id",
            label: "Contacts",
            requiresAllPermissions: [],
            requiresAnyPermissions: ["crm_contacts.create"],
          },
        },
        label: "CRM",
        requiresAllPermissions: [],
        requiresAnyPermissions: [
          "crm_forms.create",
          "crm_forms.view",
          "crm_contacts.create",
          "crm_contacts.view",
        ],
        showLabel: true,
      },
      modules: {
        children: {},
        label: "Custom Modules",
        requiresAllPermissions: [],
        requiresAnyPermissions: [],
        showLabel: true,
      },
      utilities: {
        children: {
          file_manager: {
            children: false,
            icon: "icon-folders",
            label: "File Manager",
            requiresAllPermissions: [],
            requiresAnyPermissions: ["file_manager.view"],
            route: "admin.file_manager.index",
          },
        },
        label: "Utilities",
        requiresAllPermissions: [],
        requiresAnyPermissions: ["file_manager.view"],
        showLabel: true,
      },
      settings: {
        children: {
          users: {
            activeRoutes: [
              "admin.users.index",
              "admin.users.create",
              "admin.users.edit",
            ],
            children: {
              index: {
                icon: false,
                label: "View Users",
                requiresAllPermissions: ["users.view"],
                requiresAnyPermissions: [],
                route: "admin.users.index",
              },
              create: {
                children: false,
                icon: false,
                label: "Create User",
                requiresAllPermissions: ["users.create"],
                requiresAnyPermissions: [],
                route: "admin.users.create",
              },
            },
            icon: "icon-users",
            label: "Users",
            requiresAllPermissions: [],
            requiresAnyPermissions: ["users.view", "users.create"],
            route: false,
          },
          config: {
            children: false,
            icon: "icon-settings",
            label: "Setting",
            requiresAllPermissions: [],
            requiresAnyPermissions: [],
            route: "admin.cms.config.index",
          },
          modules: {
            children: {
              index: {
                icon: false,
                label: "View Modules",
                requiresAllPermissions: [],
                requiresAnyPermissions: ["cms_advanced.view"],
                route: "admin.modules.index",
              },
              create: {
                children: false,
                icon: false,
                label: "Create Module",
                requiresAllPermissions: [],
                requiresAnyPermissions: ["cms_advanced.create"],
                route: "admin.modules.create",
              },
            },
            icon: "icon-modules",
            label: "Modules",
            requiresAllPermissions: [],
            requiresAnyPermissions: ["cms_advanced.view", "cms_advanced.create"],
            route: "admin.modules.index",
          },
        },
        label: "Settings",
        requiresAllPermissions: [],
        requiresAnyPermissions: ["users.view", "users.create"],
        showLabel: true,
      },
    },
    loadingMenu: false,
}
